add `=` for all `isystem` flags
conda-forge/clang-compiler-activation-feedstock pull request #132
Opened 2024-06-28 19:51 UTC by wolfv

Ruby has some annoying problem where it checks all CFLAGS one-by-one. I figures that `-isystem` works, but the path that follows does not work (alone). It then removes the path that follows, but that breaks compilation of other stuff later because it then reads `-isystem conftest.c` which doesn't produce working executables.

2024-06-28 20:04 UTC, h-vetinari reviewed
Gonna need to bump the build number for builds from this to be published. Otherwise okay for me

2024-06-28 20:10 UTC, isuruf requested changes
That seems like a Ruby issue to me. Please open an issue upstreamin Ruby.

2024-06-28 20:36 UTC, wolfv commented
Hmmm, ok, turns out its Nokogiri specific :(

https://github.com/sparklemotion/nokogiri/blob/85c1801e5a073c16d1822ea0d9ad00b4ad4d91e5/ext/nokogiri/extconf.rb#L673

I can also patch that out, I suppose.

2024-06-28 20:45 UTC, wolfv commented
Actually, a few other ruby extensions also seem to do it: https://github.com/search?q=append_cflags%20path%3A**%2Fextconf.rb&type=code ...

2024-07-01 21:54 UTC, wolfv commented
Just for the record, this is what the flags look like today:

```
2024-07-01T21:12:58.7308690Z +CFLAGS=-ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/zig-0.13.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
```

So both `debug-prefix-map` use the `=` after the argument. I don't think it would hurt to add the `=` after `-isystem`.

@isuruf I don't think I can reasonably fix this in Ruby as it is a problem of the build scripts. I don't see any real blockers for this PR, but if you insist I can also close it.

2024-07-01 22:01 UTC, isuruf commented
Recipes like https://github.com/conda-forge/root-feedstock/blob/1987df5fb087fb149f114dab14f6dd5f99e3156d/recipe/build.sh#L72-L80 will fail if we do this. I think it's better to fix this in Ruby. Is it only nokogiri that's being used?

2024-07-02 07:49 UTC, wolfv commented
The problem is that this is in the build script of multiple Gems.

2024-07-02 13:29 UTC, isuruf commented
It's just a matter of patching https://github.com/ruby/ruby/blob/master/lib/mkmf.rb#L1106-L1114 to consider `-isystem, -I, -J, -L, -iquote, -idirafter` to do the right thing.

2024-07-02 13:30 UTC, isuruf commented
> Hmm, but that is pretty weird usage anyways, isn't it? And they could change to replace -isystem= with -I .

Sure, but yours is a weird use as well? We shouldn't be trying to decide which one is weirder.

2024-07-02 13:33 UTC, isuruf commented
Also if you look at the docs `-isystem <PATH>` is not equivalent to `-isystem=<PATH>`

2024-07-02 14:38 UTC, wolfv commented
What if we remove the `=` but also remove the space, ie. `-isystem/foo/bla`?

I think that should be valid?

But anyways, happy to close this PR as I can patch it either in Ruby or in the recipes.

2024-08-08 15:45 UTC, wolfv commented
Closing since this is fixed in nokigiri and hopefully trickles down to more ruby packages over time.

2024-08-08 15:45 UTC, closed without merging